---
- name:     Controleren of de node repo al is geinstalleerd
  stat:     path=/etc/yum.repos.d/nodesource-el.repo
  register: node_repo_installed

- name:     Verwijderen oude NodeJS installatie
  yum:      name={{ item }} state=absent
  when:     not node_repo_installed.stat.exists
  with_items:
   - nodejs
   - npm

- name:     Install node repo
  yum:      name=http://rpm.nodesource.com/pub_5.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm state=present

- name:     Install node
  yum:      name=nodejs state=latest

- name:     Install node pakketjes
  npm:      name={{ item }} global=yes state=present
  with_items:
   - bower
   - grunt-cli
   - yarn
